language: go

go:
  - '1.13.x'

go_import_path: github.com/brancz/kube-rbac-proxy

env:
  - GO111MODULE=on

cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod

services:
  - docker

jobs:
  include:
    - stage: Integration Tests
      before_script:
        - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
        - kind create cluster --config test/e2e/kind-config/kind-config.yaml
      script:
        - VERSION=local make container
        - kind load docker-image quay.io/brancz/kube-rbac-proxy:local
        - make test-e2e
